---
version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - 'cluster.name=es-docker-cluster'
      - 'node.name=master'
      - 'discovery.zen.ping.unicast.hosts=elasticsearch'
      - 'bootstrap.memory_lock=true'
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - 'xpack.monitoring.enabled=true'
      - 'xpack.monitoring.collection.enabled=true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '0.0.0.0:9200:9200'
    networks:
      - stack

  elasticsearch_n1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - 'cluster.name=es-docker-cluster'
      - 'node.name=n1'
      - 'discovery.zen.ping.unicast.hosts=elasticsearch'
      - 'bootstrap.memory_lock=true'
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - 'xpack.monitoring.enabled=true'
      - 'xpack.monitoring.collection.enabled=true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '0.0.0.0:9201:9200'
    networks:
      - stack

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - '0.0.0.0:5601:5601'
    networks:
      - stack
    depends_on:
      - elasticsearch

networks:
  stack: ~
